### PR TITLE
Waterfall cond

### PR DESCRIPTION
**Pull request by jedwards1211**
Okay, this is my new PR complete with tests.

### CODE REVIEW

**Comment by jedwards1211** [comment]
@TheLarkInn could you guys please provide an `.eslintrc` in the future so that we can automatically `eslint --fix` little stylistic nitpicks like double quotes as required by Codacy?

**Comment by jedwards1211** [comment]
@TheLarkInn actually, sorry, I didn't notice that there is one, however, it looks like it probably doesn't have all the same rules as Codacy is using.

**Comment by jedwards1211** [comment]
@TheLarkInn does Codacy provide a way to download the ESLint config it uses?  If it were merely easy to find I would have PRed a new `.eslintrc` to this project myself.

**Comment by sokra** [comment]
old

**Pull request closed without merging**
