### PR TITLE
fix Readme typo

### PR DESCRIPTION
**Pull request by lcxfs1991**
fix Readme typo
`hander` should be `handler`

add code example for better understanding of this plugin

### CODE REVIEW

**Comment by TheLarkInn** [comment]
Thank you!!

**Comment by TheLarkInn** [comment]
LGTM

**Comment by domfarolino** [comment]
Sorry didn't see this PR. The typos were at least taken care of in https://github.com/webpack/tapable/pull/24

**Comment by sokra** [comment]
outdated

**Pull request closed without merging**
