### PR TITLE
Cannot read property 'apply' of undefined

### PR DESCRIPTION
**Pull request by rainabba**
address scenario where the value of arguments[i] is undefined

### CODE REVIEW

**Comment by gdi2290** [comment]
:+1:

**Comment by sokra** [comment]
Don't pass undefined.

**Comment by rainabba** [comment]
@sokra This was an issue that came up at an Angular presentation by PatrickJS. Windows users that cloned the project and tried to run it (like myself) saw this error while the mac users did not (even with the same version of Node, NPM, etc..) and in the end, was a simple logic issue that I submitted a PR for at https://github.com/rainabba/tapable/commit/5218309c15c0165e1c87990bb086b622df6f838e.

That said, what was the point of your comment and why is this closed without the PR being applied and while the bug exists?

**Comment by sokra** [comment]
It's maybe a bug, but not here. `apply` expects objects that have a `apply` method. The bug is maybe in a higher level which passes something wrong into `apply`.

**Comment by rainabba** [comment]
"apply expects objects that have a apply method."  So better to leave this code fragile than add the simplest of computational checks to make it more robust?

In a very real-world scenario, an entire project ran on one platform and not another because of something much higher-level (and harder to address) because this project is missing such a simple check to address an assumption you just declared.

**Comment by sokra** [comment]
> So better to leave this code fragile than add the simplest of computational checks to make it more robust?

Yes, I think so.

It's better to throw an error to indicate that there is a error on a higher level, than to silently ignore it and leave the higher level uninformed.

**Comment by gdi2290** [comment]
it seems like the preferred "fix" is to provide the user with the correct feedback (suggest that the problem is due to the plugin) otherwise you will get more issues such as this or https://github.com/webpack/webpack/issues/1632

**Comment by rainabba** [comment]
Okay. I that makes sense to me. Thanks for helping me understand. Admittedly, error handling is an error I need to improve in :)

**Comment by rainabba** [comment]
Would it make any sense to then use a similar check with an else to throw a more informative error? Any reason that wouldn't be advisable?

**Pull request closed without merging**
