### PR TITLE
Macro optimisation of copyProperties.

### PR DESCRIPTION
**Pull request by Mamoru1234**
According to  https://jsperf.com/object-keys-vs-for-in-with-closure/3 .

### CODE REVIEW

**Comment by probablyup** [comment]
This does not appear to be an axiom. img_0051

**Comment by Mamoru1234** [comment]
@probablyup What browser you are using?
I was trying on several chrome versions and each time Object.keys() was faster.

**Comment by probablyup** [comment]
Safari.

**Comment by Mamoru1234** [comment]
@probablyup Thank you for your comment.

**Pull request closed without merging**
